#!/bin/bash

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# Load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Reconfigure spaces when a display is added
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/setup_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/setup_spaces.sh"

# Trigger sketchybar on window events
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# Configure spaces
$HOME/.config/yabai/setup_spaces.sh

################################################################################
# Tiling Options ###############################################################
################################################################################

# Tile windows
yabai -m config layout bsp

# New windows spawn to the right or bottom
yabai -m config window_placement second_child

# Splitting
yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config split_type auto

# Window Padding ###############################################################

# Pad top of screen for external bar
yabai -m config external_bar all:40:0

# Window padding
yabai -m config top_padding 0
yabai -m config right_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0

# Window gap
yabai -m config window_gap 0

# Window Modifications #########################################################

# Set animation duration
yabai -m config window_animation_duration 0.0

# Floating windows are always on top
yabai -m config window_topmost on

# Only show window shadow on floating windows
yabai -m config window_shadow off

# Show new windows on the focused display
yabai -m config window_origin_display focused

# Mouse ########################################################################

# Focus window under the mouse
yabai -m config focus_follows_mouse autofocus

################################################################################
# Spaces #######################################################################
################################################################################

# Space Labels #################################################################
yabai -m space 1 --label "dashboard"     # error space

yabai -m space 2 --label "term"          # 1
yabai -m space 3 --label "web"           # 2
yabai -m space 4 --label "notes"         # 3
yabai -m space 5 --label "communication" # 4
yabai -m space 6 --label "tools"         # 5
yabai -m space 7 --label "other"         # 6
yabai -m space 8 --label "float"         # 7
yabai -m space 9 --label "spotify"       # 8

# Space Configs ################################################################

# Multiple displays
yabai -m config --space 8 layout float

# Space Rules ##################################################################

# main space

# web space
yabai -m rule --add app="^Safari$" space=web

# communication space
yabai -m rule --add app="^Spark$" space=communication
yabai -m rule --add app="^Slack$" space=communication manage=off
yabai -m rule --add app="^Microsoft Teams$" space=communication manage=off

# notes space
yabai -m rule --add app="^Obsidian$" space=notes
yabai -m rule --add app="^Notion$" space=notes

# tools space
yabai -m rule --add app="^OnyX$" space=tools
yabai -m rule --add app="^balenaEtcher$" space=tools
yabai -m rule --add app="^Xcode$" space=tools
yabai -m rule --add app="^Disk Inventory X$" space=tools
yabai -m rule --add app="^Karabiner$" space=tools

# float space
yabai -m rule --add app="^Finder$" space=float manage=off
yabai -m rule --add app="^System Information$" space=float manage=off
yabai -m rule --add app="^System Preferences$" space=float manage=off
yabai -m rule --add app="^System Settings$" space=float manage=off
yabai -m rule --add app="^zoom.us$" space=float manage=off
yabai -m rule --add app="^universalAccessAuthWarn" space=float manage=off

# spotify space
yabai -m rule --add app="^Spotify$" space=spotify

# unmanaged
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^AltTab$" manage=off
yabai -m rule --add app="^Spaced$" manage=off
yabai -m rule --add app="^Rectangle$" manage=off
yabai -m rule --add app="^Today$" manage=off
